-- Drops 'active' from activity_level, leaving four levels.
--
-- Generated by drizzle-kit, then corrected. What it produced casts the column
-- to text, drops the type, rebuilds it without 'active', and casts back — and
-- never moves the rows that hold the value being removed. On an empty database
-- that passes. On any database with a user who picked 'active' it fails on the
-- last statement, because there is no longer a value to cast that text to.
--
-- The UPDATE below is the missing step. It sits where it does on purpose: the
-- column is plain text by then, so it is an ordinary string comparison and
-- needs no enum that still contains the value.
--
-- 'active' (1.725) folds DOWN into 'moderate' (1.55) rather than up into
-- 'very_active' (1.9). Both are wrong for whoever picked it — that is the cost
-- of removing a rung — but they are not equally wrong. A target set too low
-- gets noticed, because hunger is a signal; one set too high does not, because
-- eating to a number that was never right is invisible until the weight goes
-- the wrong way. It is the same reasoning the onboarding copy gives the user
-- when it tells them to pick low if they are unsure.

ALTER TABLE "public"."user_profiles" ALTER COLUMN "activity_level" SET DATA TYPE text;--> statement-breakpoint
UPDATE "public"."user_profiles" SET "activity_level" = 'moderate' WHERE "activity_level" = 'active';--> statement-breakpoint
DROP TYPE "public"."activity_level";--> statement-breakpoint
CREATE TYPE "public"."activity_level" AS ENUM('sedentary', 'light', 'moderate', 'very_active');--> statement-breakpoint
ALTER TABLE "public"."user_profiles" ALTER COLUMN "activity_level" SET DATA TYPE "public"."activity_level" USING "activity_level"::"public"."activity_level";
